export const DarkMode = {
    "color-primary": "#409eff",
    "color-success": "#67c23a",
    "color-warning": "#e6a23c",
    "color-danger": "#f56c6c",
    "color-info": "#909399",
    "color-primary-text": "#ffffff",
    "color-regular-text": "#606266",
    "color-secondary-text": "#909399",
    "color-placeholder": "#c0c4cc",
    "color-border-darker": "#b0bec5",
    "color-border-base": "#11131B",
    "color-border-lighter": "#eceff1",
    "color-background-darker": "#1B1E2B",
    "color-background-base": "#292D3E",
    "color-background-lighter": "#f5f5f5",
    "color-black": "#000000",
    "color-white": "#ffffff",
};
